### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Shakir-Hussain12** [Shakir-Hussain12/Mobile-Portfolio#10]
**Link to online GitHub pages deployment:**
---
 https://shakir-hussain12.github.io/Mobile-Portfolio/

**Comment by jerryowusu** [comment]
Hi @Shakir-Hussain12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200w](https://user-images.githubusercontent.com/65233860/207023130-00c61dbc-73ba-4db0-8024-39dd3b8e311f.gif)


## Highlights
Project deployed successfully :+1: 
Great effort :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
